global:
  scrape_interval:     15s

  external_labels:
    monitor: 'firehose-monitor'

scrape_configs:
  - job_name: 'firehose-metrics'
    scrape_interval: 5s
    metrics_path: '/firehose/resources/metrics/'
    static_configs:
      - targets: ['firehose:8080']